services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=yourStrong(!)Password
      - POSTGRES_DB=Database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  migrator:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    container_name: migrator
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - POSTGRESQL_CONNECTION_STRING=Host=postgresql;Database=Database;Username=postgres;Password=yourStrong(!)Password
    restart: "no"
    networks:
      - app-network

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      migrator:
        condition: service_completed_successfully
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Api__PostgreSQLConnectionString=Host=postgresql;Database=Database;Username=postgres;Password=yourStrong(!)Password
      - Api__Url=http://0.0.0.0:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge